Plugin Framework outline
kupiakos/CS340 pull request #93
Opened 2016-12-01 17:11 UTC by Audakel

Added the abstract interfaces for how I thought a plugin system could work for this project. It handles any type of plugin, not only persistance type plugins.

2016-12-01 18:20 UTC, kupiakos commented on .gitignore
> +.idea/
These should not be here, as before.

2016-12-03 08:24 UTC, kupiakos commented
Shouldn't fc75e4a only be in the `checkstyle` branch?

2016-12-03 18:52 UTC, Audakel commented
yeah i removed the style stuff now

2016-12-03 19:20 UTC, kupiakos requested changes

2016-12-03 19:20 UTC, kupiakos commented on java/Phase 1.iml
> +    <orderEntry type="library" name="checkstyle-7.3-all" level="project" />
Still have the library defined.

2016-12-03 19:20 UTC, kupiakos commented on java/src/server/plugin/IPluginLoader.java
> +    ArrayList<IPlugin> loadConfig(ArrayList<PluginConfig> configs);
These should be returning `List`

2016-12-03 21:46 UTC, Audakel commented
ok try that

2016-12-03 22:07 UTC, Audakel commented
Fixed ArrayList

2016-12-03 22:15 UTC, merged